apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ihd-chatbotback-pvc
  namespace: ihd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: static-nks-nas-csi-encryption
  volumeMode: Filesystem
  volumeName: ihd-chatbotback-pv